### ISSUE TITLE
change profile avatar 

### ISSUE THREAD

**Issue by starli-ai** [Rajatm544/MERN-Ecommerce#1]
User Change avatar has error  and doesnt work it .

**Comment by Rajatm544** [comment]
I am able to upload a new pic for the user avatar from the profile page. 

Can you provide steps to replicate the error, in case you're still experiencing it?

**Comment by starli-ai** [comment]
i change aws to cloudinary in backend and work it  in backend but doestn work in frontend

**Comment by starli-ai** [comment]
from client image upload to cloudinary but nothing change in profile

**Comment by starli-ai** [comment]
everything okay . thank you
